In [372]:
import pandas as pd

In [406]:
df = pd.read_csv("playerStats.csv")
df.head()

,Unnamed: 0,weekNumber,totalPoints,isInIdealFormation,playerTeam,playerName,mins_played,goals,goal_assist,offtarget_att_assist,...,goals_conceded,yellow_card,second_yellow_card,red_card,total_scoring_att,won_contest,ball_recovery,poss_lost_all,penalty_conceded,marca_points
0,0,1.0,2.0,False,Granada CF,Melendo,58,0,0,0,...,1,0,0,0,0,0,3,8,0,-1
1,1,2.0,2.0,False,Granada CF,Melendo,80,0,0,0,...,2,0,0,0,0,1,2,5,0,-1
2,2,3.0,0.0,False,Granada CF,Melendo,83,0,0,0,...,1,1,0,0,0,0,2,5,1,-1
3,3,4.0,0.0,False,Granada CF,Melendo,24,0,0,0,...,2,0,0,0,0,0,0,1,0,-1
4,4,5.0,1.0,False,Granada CF,Melendo,74,0,0,0,...,3,1,0,0,0,1,7,5,0,-1

In [407]:
df = df.drop('Unnamed: 0', axis = 1)
df.head()

,weekNumber,totalPoints,isInIdealFormation,playerTeam,playerName,mins_played,goals,goal_assist,offtarget_att_assist,pen_area_entries,...,goals_conceded,yellow_card,second_yellow_card,red_card,total_scoring_att,won_contest,ball_recovery,poss_lost_all,penalty_conceded,marca_points
0,1.0,2.0,False,Granada CF,Melendo,58,0,0,0,0,...,1,0,0,0,0,0,3,8,0,-1
1,2.0,2.0,False,Granada CF,Melendo,80,0,0,0,0,...,2,0,0,0,0,1,2,5,0,-1
2,3.0,0.0,False,Granada CF,Melendo,83,0,0,0,0,...,1,1,0,0,0,0,2,5,1,-1
3,4.0,0.0,False,Granada CF,Melendo,24,0,0,0,0,...,2,0,0,0,0,0,0,1,0,-1
4,5.0,1.0,False,Granada CF,Melendo,74,0,0,0,0,...,3,1,0,0,0,1,7,5,0,-1

In [379]:
df['isInIdealFormation'] = df['isInIdealFormation'].map({False: 0, True: 1})

In [380]:
df['isInIdealFormation']

0        0
1        0
2        0
3        0
4        0
        ..
10051    0
10052    0
10053    0
10054    0
10055    0
Name: isInIdealFormation, Length: 10056, dtype: int64

In [381]:
X = df.drop(['totalPoints', 'playerName', 'playerTeam', 'weekNumber'], axis = 1)
y = df['totalPoints']

In [382]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [383]:
from sklearn.svm import SVR
svr = SVR()
svr.fit(X_train, y_train)

SVR()

In [384]:
y_pred = svr.predict(X_test)

In [385]:
playerPredicted = df[(df['playerName'] == 'Gerard') & (df['weekNumber'] == 16)]
playerPredicted

,weekNumber,totalPoints,isInIdealFormation,playerTeam,playerName,mins_played,goals,goal_assist,offtarget_att_assist,pen_area_entries,...,goals_conceded,yellow_card,second_yellow_card,red_card,total_scoring_att,won_contest,ball_recovery,poss_lost_all,penalty_conceded,marca_points
4817,16.0,1.0,0,Villarreal,Gerard,89,0,0,0,0,...,3,0,0,0,1,1,2,13,0,-1

In [386]:
playerPredicted = playerPredicted.drop(['weekNumber', 'totalPoints', 'playerTeam', 'playerName'], axis = 1)

In [387]:
gerardPrediction = svr.predict(playerPredicted)
gerardPrediction

array([2.4391907])

In [388]:
playerPredictionsBasedOnLastWeek = df[df["weekNumber"] == 24]
playerPredictionsBasedOnLastWeek.head(10)

,weekNumber,totalPoints,isInIdealFormation,playerTeam,playerName,mins_played,goals,goal_assist,offtarget_att_assist,pen_area_entries,...,goals_conceded,yellow_card,second_yellow_card,red_card,total_scoring_att,won_contest,ball_recovery,poss_lost_all,penalty_conceded,marca_points
23,24.0,2.0,0,Granada,Melendo,75,0,0,0,0,...,2,0,0,0,0,2,4,10,0,-1
52,24.0,9.0,0,Granada,"Miquel, I",90,0,0,0,0,...,3,1,0,0,1,1,6,9,0,-1
54,24.0,14.0,1,Granada,Pellistri,84,0,1,0,1,...,3,0,0,0,2,0,6,10,0,-1
77,24.0,1.0,0,Granada,"Gumbau, Gerard",89,0,0,0,1,...,3,0,0,0,0,1,2,10,0,-1
98,24.0,2.0,0,Granada,"Torrente, Raul",1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,-1
123,24.0,7.0,0,Granada,"Uzuni, Myrto",84,0,1,1,0,...,3,0,0,0,1,0,1,5,0,-1
130,24.0,2.0,0,Granada,"Arezo, Matias",6,0,0,0,0,...,0,0,0,0,0,0,0,1,0,-1
156,24.0,4.0,0,Granada,"Hongla, Martin",90,0,0,0,0,...,3,0,0,0,0,0,10,6,0,-1
183,24.0,0.0,0,Granada,"Rubio, Miguel",90,0,0,0,0,...,3,0,0,0,0,0,7,9,0,-1
208,24.0,2.0,0,Granada,"Callejon, Jose",15,0,0,0,1,...,1,0,0,0,0,0,3,3,0,-1

In [389]:
playerPredictions = playerPredictionsBasedOnLastWeek.drop(['weekNumber', 'totalPoints', 'playerTeam', 'playerName'], axis = 1)

array([5.35289853])

In [390]:
playerPredictionsScores = svr.predict(playerPredictions)

In [391]:
import numpy as np

In [392]:
playerPredictionsScores = np.around(playerPredictionsScores, decimals=0)

In [393]:
df_predBasedOnLastWeek = pd.DataFrame({'playerName': playerPredictionsBasedOnLastWeek['playerName'],'playerTeam': playerPredictionsBasedOnLastWeek['playerTeam'], 'predicted_pointsBasedOnLastWeek': playerPredictionsScores})
df_predBasedOnLastWeek.head(10)

         playerName playerTeam  predicted_pointsBasedOnLastWeek
23          Melendo    Granada                              3.0
52        Miquel, I    Granada                              4.0
54        Pellistri    Granada                              4.0
77   Gumbau, Gerard    Granada                              3.0
98   Torrente, Raul    Granada                              0.0
123    Uzuni, Myrto    Granada                              3.0
130   Arezo, Matias    Granada                              1.0
156  Hongla, Martin    Granada                              4.0
183   Rubio, Miguel    Granada                              3.0
208  Callejon, Jose    Granada                              2.0

In [394]:
playerPredictionsBasedOnLastWeek.shape

(425, 26)

In [395]:
df_predBasedOnLastMatch = playerPredictionsBasedOnLastWeek = df[df["weekNumber"] == 1]
df_predBasedOnLastMatch.head(10)

,weekNumber,totalPoints,isInIdealFormation,playerTeam,playerName,mins_played,goals,goal_assist,offtarget_att_assist,pen_area_entries,...,goals_conceded,yellow_card,second_yellow_card,red_card,total_scoring_att,won_contest,ball_recovery,poss_lost_all,penalty_conceded,marca_points
0,1.0,2.0,0,Granada,Melendo,58,0,0,0,0,...,1,0,0,0,0,0,3,8,0,-1
25,1.0,2.0,0,Granada,"Vallejo, Jesus",90,0,0,0,0,...,3,0,0,0,0,1,7,7,0,-1
29,1.0,0.0,0,Granada,"Miquel, I",90,0,0,0,0,...,3,0,0,0,0,0,2,11,0,-1
56,1.0,0.0,0,Granada,"Gumbau, Gerard",74,0,0,0,0,...,2,1,0,0,0,0,2,19,0,-1
100,1.0,2.0,0,Granada,"Uzuni, Myrto",90,0,0,0,0,...,3,0,0,0,2,0,3,10,0,-1
132,1.0,7.0,0,Granada,"Villar, G",32,0,1,1,0,...,2,0,0,0,0,0,2,7,0,-1
158,1.0,0.0,0,Granada,"F, Raul",0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,-1
167,1.0,3.0,0,Granada,"Rubio, Miguel",90,0,0,0,0,...,3,0,0,0,0,0,9,7,0,-1
185,1.0,3.0,0,Granada,"Callejon, Jose",74,0,0,0,1,...,2,0,0,0,0,0,6,11,0,-1
210,1.0,3.0,0,Granada,"Ruiz, Sergio",90,0,0,0,0,...,3,0,0,0,0,0,10,10,0,-1

In [396]:
from sklearn.metrics import mean_absolute_error

In [397]:
mean_absolute_error(y_test, y_pred)

1.4483679553613993

In [398]:
df

,weekNumber,totalPoints,isInIdealFormation,playerTeam,playerName,mins_played,goals,goal_assist,offtarget_att_assist,pen_area_entries,...,goals_conceded,yellow_card,second_yellow_card,red_card,total_scoring_att,won_contest,ball_recovery,poss_lost_all,penalty_conceded,marca_points
0,1.0,2.0,0,Granada,Melendo,58,0,0,0,0,...,1,0,0,0,0,0,3,8,0,-1
1,2.0,2.0,0,Granada,Melendo,80,0,0,0,0,...,2,0,0,0,0,1,2,5,0,-1
2,3.0,0.0,0,Granada,Melendo,83,0,0,0,0,...,1,1,0,0,0,0,2,5,1,-1
3,4.0,0.0,0,Granada,Melendo,24,0,0,0,0,...,2,0,0,0,0,0,0,1,0,-1
4,5.0,1.0,0,Granada,Melendo,74,0,0,0,0,...,3,1,0,0,0,1,7,5,0,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10051,22.0,0.0,0,Getafe CF,Oscar,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,-1
10052,20.0,0.0,0,Getafe CF,Oscar,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,-1
10053,23.0,0.0,0,Getafe CF,Oscar,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,-1
10054,24.0,0.0,0,Getafe CF,Oscar,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,-1
10055,25.0,0.0,0,Getafe CF,Oscar,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,-1

In [399]:
promedio_por_jugador = df.iloc[:,4:26].groupby('playerName').agg('mean').reset_index()
promedio_por_jugador['isInIdealFormation'] = 0
ultima_columna = promedio_por_jugador.columns[-1]
nuevo_orden_columnas = [ultima_columna] + [col for col in promedio_por_jugador.columns if col != ultima_columna]
promedio_por_jugador = promedio_por_jugador.reindex(columns=nuevo_orden_columnas)
promedio_por_jugador

,isInIdealFormation,playerName,mins_played,goals,goal_assist,offtarget_att_assist,pen_area_entries,penalty_won,penalty_save,saves,...,goals_conceded,yellow_card,second_yellow_card,red_card,total_scoring_att,won_contest,ball_recovery,poss_lost_all,penalty_conceded,marca_points
0,0,A,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,...,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,-1.0
1,0,Abde,36.950000,0.0,0.000000,0.000000,0.100000,0.0,0.0,0.0,...,0.300000,0.050000,0.0,0.0,0.250000,1.000000,1.850000,8.950000,0.000000,-1.0
2,0,Abdon,34.576923,0.0,0.038462,0.153846,0.038462,0.0,0.0,0.0,...,0.461538,0.115385,0.0,0.0,0.346154,0.269231,1.000000,4.807692,0.000000,-1.0
3,0,Abner,50.565217,0.0,0.000000,0.043478,0.086957,0.0,0.0,0.0,...,0.652174,0.130435,0.0,0.0,0.000000,0.217391,3.304348,7.826087,0.043478,-1.0
4,0,Abqar,75.526316,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,...,1.000000,0.315789,0.0,0.0,0.105263,0.157895,4.473684,7.157895,0.105263,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
533,0,"Zakharyan, Arsen",36.294118,0.0,0.058824,0.058824,0.764706,0.0,0.0,0.0,...,0.352941,0.000000,0.0,0.0,0.235294,0.294118,1.941176,7.176471,0.000000,-1.0
534,0,Zaldua,13.458333,0.0,0.000000,0.000000,0.041667,0.0,0.0,0.0,...,0.250000,0.041667,0.0,0.0,0.000000,0.000000,0.541667,1.708333,0.000000,-1.0
535,0,"Zubeldia, Igor",82.833333,0.0,0.083333,0.000000,0.041667,0.0,0.0,0.0,...,0.875000,0.375000,0.0,0.0,0.000000,0.166667,6.291667,9.500000,0.000000,-1.0
536,0,Zubimendi,85.708333,0.0,0.041667,0.041667,0.000000,0.0,0.0,0.0,...,0.875000,0.125000,0.0,0.0,0.458333,0.375000,6.708333,8.541667,0.000000,-1.0
537,0,"de Frutos, Jorge",28.291667,0.0,0.000000,0.041667,0.458333,0.0,0.0,0.0,...,0.458333,0.000000,0.0,0.0,0.291667,0.291667,1.750000,4.500000,0.000000,-1.0

In [400]:
promedio_por_jugador_predictor = promedio_por_jugador.drop('playerName', axis = 1)
promedio_por_jugador_predictor

,isInIdealFormation,mins_played,goals,goal_assist,offtarget_att_assist,pen_area_entries,penalty_won,penalty_save,saves,effective_clearance,...,goals_conceded,yellow_card,second_yellow_card,red_card,total_scoring_att,won_contest,ball_recovery,poss_lost_all,penalty_conceded,marca_points
0,0,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,...,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,-1.0
1,0,36.950000,0.0,0.000000,0.000000,0.100000,0.0,0.0,0.0,0.150000,...,0.300000,0.050000,0.0,0.0,0.250000,1.000000,1.850000,8.950000,0.000000,-1.0
2,0,34.576923,0.0,0.038462,0.153846,0.038462,0.0,0.0,0.0,0.269231,...,0.461538,0.115385,0.0,0.0,0.346154,0.269231,1.000000,4.807692,0.000000,-1.0
3,0,50.565217,0.0,0.000000,0.043478,0.086957,0.0,0.0,0.0,1.739130,...,0.652174,0.130435,0.0,0.0,0.000000,0.217391,3.304348,7.826087,0.043478,-1.0
4,0,75.526316,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,3.789474,...,1.000000,0.315789,0.0,0.0,0.105263,0.157895,4.473684,7.157895,0.105263,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
533,0,36.294118,0.0,0.058824,0.058824,0.764706,0.0,0.0,0.0,0.117647,...,0.352941,0.000000,0.0,0.0,0.235294,0.294118,1.941176,7.176471,0.000000,-1.0
534,0,13.458333,0.0,0.000000,0.000000,0.041667,0.0,0.0,0.0,0.333333,...,0.250000,0.041667,0.0,0.0,0.000000,0.000000,0.541667,1.708333,0.000000,-1.0
535,0,82.833333,0.0,0.083333,0.000000,0.041667,0.0,0.0,0.0,3.458333,...,0.875000,0.375000,0.0,0.0,0.000000,0.166667,6.291667,9.500000,0.000000,-1.0
536,0,85.708333,0.0,0.041667,0.041667,0.000000,0.0,0.0,0.0,1.791667,...,0.875000,0.125000,0.0,0.0,0.458333,0.375000,6.708333,8.541667,0.000000,-1.0
537,0,28.291667,0.0,0.000000,0.041667,0.458333,0.0,0.0,0.0,0.166667,...,0.458333,0.000000,0.0,0.0,0.291667,0.291667,1.750000,4.500000,0.000000,-1.0

In [401]:
playerPredictionsScores = np.around(svr.predict(promedio_por_jugador_predictor), decimals = 0)
df_predBasedOnAverage = pd.DataFrame({'playerName2': promedio_por_jugador['playerName'], 'predicted_pointsBasedOnAverage': playerPredictionsScores})
df_predBasedOnAverage.head(10)

            playerName2  predicted_pointsBasedOnAverage
0                     A                             0.0
1                  Abde                             2.0
2                 Abdon                             2.0
3                 Abner                             3.0
4                 Abqar                             4.0
5              Acuna, M                             3.0
6                 Adria                             0.0
7      Adu-ares, Malcom                             1.0
8        Agoume, Lucien                             4.0
9  Aguirrezabala, Julen                             0.0

In [404]:
df_ForPredictions = pd.concat([df_predBasedOnAverage,df_predBasedOnLastWeek], axis = 1)
df_ForPredictions

,playerName2,predicted_pointsBasedOnAverage,playerName,playerTeam,predicted_pointsBasedOnLastWeek
0,A,0.0,NaN,NaN,NaN
1,Abde,2.0,NaN,NaN,NaN
2,Abdon,2.0,NaN,NaN,NaN
3,Abner,3.0,NaN,NaN,NaN
4,Abqar,4.0,NaN,NaN,NaN
...,...,...,...,...,...
9974,NaN,NaN,"Maksimovic, Nemanja",Getafe CF,4.0
9997,NaN,NaN,Mata,Getafe CF,3.0
10020,NaN,NaN,"Duarte, Domingos",Getafe CF,0.0
10034,NaN,NaN,"Milla, L",Getafe CF,5.0
10054,NaN,NaN,Oscar,Getafe CF,0.0

In [405]:
df_ForPredictions.to_csv("playerPredictions.csv")

In [403]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test, y_pred)

1.4483679553613993